export const GET_DOUBT_REQUEST = 'GET_DOUBT_REQUEST';
export const GET_DOUBT_SUCCESS = 'GET_DOUBT_SUCCESS';
export const GET_DOUBT_FAILURE = 'GET_DOUBT_FAILURE';

export const POST_DOUBT_REQUEST = 'POST_DOUBT_REQUEST';
export const POST_DOUBT_SUCCESS = 'POST_DOUBT_SUCCESS';
export const POST_DOUBT_FAILURE = 'POST_DOUBT_FAILURE';

export const EDIT_DOUBT_REQUEST = 'EDIT_DOUBT_REQUEST';
export const EDIT_DOUBT_SUCCESS = 'EDIT_DOUBT_SUCCESS';
export const EDIT_DOUBT_FAILURE = 'EDIT_DOUBT_FAILURE';

export const DELETE_DOUBT_REQUEST = 'DELETE_DOUBT_REQUEST';
export const DELETE_DOUBT_SUCCESS = 'DELETE_DOUBT_SUCCESS';
export const DELETE_DOUBT_FAILURE = 'DELETE_DOUBT_FAILURE';

